### ISSUE TITLE
Required Android version in README is wrong

### ISSUE THREAD

**Issue by Harteex** [molinch/FFImageLoading#8]
The README states "The library works starting from Android 4 ..."

However, it does not work on versions before 4.1.
On 4.3 everything works fine.
On 4.0.3 I get:
"java.lang.NoSuchMethodError: no method with name='getAdjustViewBounds' signature='()Z' in class Landroid/widget/ImageView;"

This method was added in API 16 (4.1): http://androidapi.xamarin.com/index.aspx?link=P%3AAndroid.Widget.ImageView.AdjustViewBounds

So possible solutions are either if it's possible to work around this, or if you could update the readme to say that it requires at least 4.1.
(unless it's me doing something wrong)

**Comment by molinch** [comment]
Hi @Harteex thanks for reporting this!
It is a regression coming from this commit https://github.com/molinch/FFImageLoading/commit/a4c15bf05aca678898d6a0b2d9f4a2b87a367e13

That shouldn't take long to fix

**Comment by molinch** [comment]
Fixed & NuGet 1.0.8 created
